import { FC } from 'react';
import './globals.scss'
import Navbar from '@/components/navbar/Navbar';
import AsideBar from '@/components/asideBar/AsideBar';

export const metadata = {
  title: 'Twitter',
  description: 'Generated by Hammani',
  icons: {
    icon: [{ url: "/assets/imgs/logo.png", }]
  }
}

type RootLayoutProps = {
  children: React.ReactNode;
}

const RootLayout:FC<RootLayoutProps> = ({children}) => {
  return (
    <html lang="en" className='dark'>
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
      </head>
      <body className='bg-white dark:bg-dim-900 dark:text-white'>
        <div className="container h-screen flex xl:max-w-[1200px]">
          {/* --- Left Navbar --- */}
          <Navbar/>

          {/* --- Content --- */}
          <div className='w-full xl:w-1/2 h-screen overflow-y-auto'>
            {children}
          </div>

          {/* --- Right Aside --- */}
          <AsideBar/>
        </div>
      </body>
    </html>
  )
}

export default RootLayout;
